class G:
    # Ttx: mean interarrival time b/n txns generated by peer
    Ttx = 0
    # Tk: mean mining time of a block
    Tk = 0
    LOW_HASH_POWER = 0.05
    HIGH_HASH_POWER = 0.5
    TRANSACTION_SIZE = 1
    MINING_FEE = 0
    # max allowed size for a block in KB
    max_size = 1024
    # a static variable for unique peer id, incremented on every new peer
    peer_counter = 0
    # total no of peers in the network
    total_peers = 0
    peers = []
    # a static variable for unique block id, incremented on every new block
    blk_counter = 0
    # Assuming TRANSACTION_SIZE is a constant

    # pointer to the genesis block
    global_genesis = None   # Block
    MINING_FEE = 0  # Assuming MINING_FEE is a constant


    START_TIME = 0.0
    MAX_BLOCK_SIZE = 1000
    TRANSACTION_SIZE = 1
    DBL_MAX = float('inf')
    INT_MAX = float('inf')

    # a static variable for unique txn id, incremented on every new txn
    txn_counter = 0